#!/usr/bin/env bash
# Configures and Install HAProxy
sudo apt-get update -y
sudo apt-get -y install haproxy
#front-end listener
echo -e "\nfrontend Server\n\tbind *:80\n\tmode http\n\tdefault_backend My_Web_Servers\n\n" | sudo tee -a /etc/haproxy/haproxy.cfg
#back-end web severs
echo -e "backend My_Web_Servers\n\tbalance roundrobin\n\tserver web-01 35.237.183.49:80 check\n\tserver web-02 52.201.229.129:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
