#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid
# and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo $$ > /var/run/holbertonscript.pid
trap sigterm 15
sigterm()
{
    echo "I hate the kill command"
    rm -rf /var/run/holbertonscript.pid
}
trap sigint 2
sigint()
{
    echo "Y U no love me?!"
}
trap sigquit 3
sigquit()
{
    rm -rf /var/run/holbertonscript.pid
    exit 0
}
while ((1))
do
    echo "To infinity and beyond"
    sleep 2
done
