#!/usr/bin/env bash
# read the file etc/passwd and show only the username
# user id, and home directory path for the user
file="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d ":" -f 1,3,6
done < "$file"
