#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times using a while loop
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Holberton School for the other iterations
i=-5
while [ $i -lt 5 ]
do
    if [ $i == 2 ]
    then
	echo "good luck"
    elif [ $i == -2 ]
	then
	echo "bad luck"
    else
	echo "Holberton School"
    fi
    ((i++))
done
