#!/usr/bin/env bash
# Check if a file exists and give info about it
file="holbertonschool"
if [ -f $file ] || [ -d $file ];
then
    echo "holbertonschool file exists"
    if [ ! -s $file ]
    then
	echo "holbertonschool file is empty"
    else
	echo "holbertonschool file is not empty"
    fi
    if [ -f $file ]
    then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
