#!/usr/bin/env bash
# Script to execute nginx with other nginx, to this case "nginx" user
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
chmod ago+rw /etc/nginx/nginx.conf
sed -i "1iuser nginx" /etc/nginx/nginx.conf
pkill -f apache2
sudo -u nginx service nginx start
