#!/usr/bin/env bash
# Script to execute nginx with other nginx, to this case "nginx" user
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
chmod 204 /etc/nginx/nginx.conf
kill -f apache2
sudo -u nginx service nginx start
